---
title: "About this blog"
description: |
  Why bother?
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I like financial markets; so much so that I have spent five years of my life to better understand one important driver of them, discount rates, by writing a [dissertation](https://mediatum.ub.tum.de/1192155) at the Technical University of Munich. And after finishing my dissertation, I started to work in the finance industry, at [Montana Capital Partners](https://www.montana-capital-partners.eu/), a firm that is focused on secondaries in private equity. In a nutshell, I try to make good investments for our investors such as pension funds, insurance companies and sovereign wealth funds.

While writing my dissertation, I had plenty of time to run data analyses on large data sets, something I not only thoroughly enjoy, but something that I also find very insightful. At my current job, I still aim to improve my work with data-driven analyses, but there is only so much time you have between internal discussions, external meetings and calls, and day-to-day tasks. 

Fortunately, my wife enjoys puzzling more than I do, which gives me a few hours a week to spend my time thinking about financial markets and related topics and how to support my thoughts with data. I have also noticed that writing these thoughts down results in higher quality and clarity. That's why I decided to start this blog. And hopefully, some of you find it helpful. I know that most certainly I will find it helpful... I'm often shocked how fast I can forget things that I looked into previously. As such, some posts will also be simple tutorials on how to do certain things in [R](https://www.r-project.org/), the data analysis software of my choice. And it's also great for blogging; this blog was created with the awesome [Distill](https://rstudio.github.io/distill/) package.

Why did I choose the name of the blog "Uncertain times"? As a gentle reminder that there is only one thing for certain about the times to come, which after all drive current valuations in the financial markets: that they are uncertain. Hence, I'm quite confident that I can keep the blog title, and that's great, because there aren't too many other things I'm certain about.

**Disclaimer:** Any opinions I express in this blog are mine and do not represent in any way the opinions of anyone else, including my employer.

