---
title: "The gross-net spread of private equity funds"
description: |
  What should be the gross-net spread of private equity funds both in terms of TVPI and DPI? What are the factors explaining it?
author:
  - name: Christoph Jäckel
    url: {}
date: 08-21-2022
output:
  distill::distill_article:
    self_contained: false
categories:
  - Private Equity
  - Data
  - Research
draft: true
bibliography: C:/Users/Christoph Jaeckel/Desktop/CJaeckel Blog/Blog/docs/biblio.bib
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(data.table)

DT <- readRDS("C:/Users/Christoph Jaeckel/Desktop/Preqin/preqin_data_16Feb2022.rds")


```

How do you translate gross performance metrics to net numbers for private equity (PE) funds? Conceptually, it's easy: consider all fees - most importantly, management and incentive / performance fees, i.e., carried interest - and expenses. Practically, it is cumbersome. You should be able to get from a gross to net TVPI, or multiple, with a back-of-the-envelope calculation. Just add c. 0.1x to the invested cost for the fees / expenses and reduce the gains by the carry percentage, typically 20%, if the fund has performed well. But good luck doing this on your envelope for the IRR.

There are several studies that discuss the gross-net spread for PE funds in more detail, such as @phalippou-gottschalg:2009 and 

Idea is similar to your [https://www.privatefundscfo.com/big-impact-credit-lines-fund-performance-really/](credit line paper). Use preqin funds as starting point, model fees and carry on top of it. Compare gross / net spread. Helpful especially for IRR.

Start with @phalippou-gottschalg:2009 that say it is 6% p.a. or McKinsey (2017) CEM Benchmarking study that apparently shows that the total fees of PE are 5.7%. Check also Gompers / Lenrner (1999) and Metrick / Yasuda (2007), which Phalippou / Gottschalg cite. My best guess for the large spread is that fees are on committed, while the impact on performance is on invested and the two can differ profoundly; however, it would be great to show this.

@phalippou-gottschalg:2009: 6% p.a. fees, two-thirds from management fees, one-third from incentive fees, more than 25% of value invested.


